name: chronoshot
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Game Engine - Stable Version
  flame: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints - Stable Version
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
