name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter (old stable version)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'   # 👈 Purana stable version use karo
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze

      - name: Build APK (release)
        run: flutter build apk --release
