name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Flutter (latest stable)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 3. Enable flutter caching
      - name: Flutter pub get
        run: flutter pub get

      # 4. Analyze code
      - name: Analyze
        run: flutter analyze

      # 5. Run tests (optional)
      - name: Run tests
        run: flutter test || true  # ignore errors if you don't use tests

      # 6. Build APK (release)
      - name: Build APK
        run: flutter build apk --release

      # 7. Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: chronoshot-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
